// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';

export function Add(arg1:task.Task):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function GetAll():Promise<Array<task.Task>>;

export function Update(arg1:task.Task):Promise<void>;
