// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['task']['Handler']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['task']['Handler']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['task']['Handler']['GetAll']();
}

export function Update(arg1) {
  return window['go']['task']['Handler']['Update'](arg1);
}
